# Generated by Django 2.1.4 on 2019-02-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.TextField()),
                ('node_id', models.TextField()),
            ],
            options={
                'db_table': 'state',
            },
        ),
    ]
